name: Example Github Actions

on:
  push:
    branches: 'main'

jobs:
  primer-paso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run ls
      run: ls -lha
      
    - name: Run env
      run: env      

    - name: Create empty file
      run: touch file_example

    - name: ls 
      run: ls -lha

    - name: Create tar file
      run: tar -czvf example.tar.gz *

    - name: Run ls
      run: ls -lha      

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: example.tar.gz

  creando-paquete:
    needs: primer-paso
    runs-on: ubuntu-latest
    steps:
    - name: list
      run: ls -lha 

    - uses: actions/download-artifact@v3
      with:
        name: my-artifact

    - name: List
      run: ls -lha
