name: Example Github Actions

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run ls
      run: ls -lha

    - name: Create empty file
      run: touch file_example

    - name: ls 
      run: ls -lha

    - name: download file
      run: wget https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.3.0-amd64-netinst.iso

    - name: Create tar file
      run: tar -czvf example.tar.gz *

    - name: Run ls
      run: ls -lha      

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: example.tar.gz
