name: Example Github Actions

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run ls
      run: ls -lha

    - name: Create empty file
      run: touch file_example
