name: Example Github Actions

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run ls
      run: ls -lha

    - name: Create file
      run: tar -czvf example.tar.gz *

    - name: Run ls
      run: ls -lha      

  create-pakage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: List
      run: ls -lha